{"name": "test_CredKart_Login_parms_003[getDataforLogin2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <testCases.test_Login_params.Test_CredKart_Login_params object at 0x0000029F9254E8A0>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"c027018ef95d152f24d859d623f612f4\")>\ngetDataforLogin = ('Credence@234test.com', 'Credence@9656')\n\n    def test_CredKart_Login_parms_003(self, setup, getDataforLogin):\n    \n        self.driver = setup\n        self.driver.get(\"https://automation.credence.in/login\")\n        self.driver.maximize_window()\n        self.driver.find_element(By.XPATH, \"//input[@id='email']\").send_keys(getDataforLogin[0])\n        self.driver.find_element(By.XPATH, \"//input[@id='password']\").send_keys(getDataforLogin[1])\n        self.driver.find_element(By.XPATH, \"//button[@type='submit']\").click()\n        try:\n>           self.driver.find_element(By.XPATH, \"//h2[normalize-space()='CredKart']\")\n\ntestCases\\test_Login_params.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:741: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:347: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x0000029F92462330>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such element\",\"message\":\"no such element: Unable to locate element: {\\...07FF7A4B69B94]\\\\n\\\\tBaseThreadInitThunk [0x00007FFF7A33257D+29]\\\\n\\\\tRtlUserThreadStart [0x00007FFF7B7AAA58+40]\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//h2[normalize-space()='CredKart']\"}\nE         (Session info: chrome=123.0.6312.106); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       \tGetHandleVerifier [0x00007FF7A4C07032+63090]\nE       \t(No symbol) [0x00007FF7A4B72C82]\nE       \t(No symbol) [0x00007FF7A4A0EC65]\nE       \t(No symbol) [0x00007FF7A4A5499D]\nE       \t(No symbol) [0x00007FF7A4A54ADC]\nE       \t(No symbol) [0x00007FF7A4A95B37]\nE       \t(No symbol) [0x00007FF7A4A7701F]\nE       \t(No symbol) [0x00007FF7A4A93412]\nE       \t(No symbol) [0x00007FF7A4A76D83]\nE       \t(No symbol) [0x00007FF7A4A483A8]\nE       \t(No symbol) [0x00007FF7A4A49441]\nE       \tGetHandleVerifier [0x00007FF7A50025AD+4238317]\nE       \tGetHandleVerifier [0x00007FF7A503F70D+4488525]\nE       \tGetHandleVerifier [0x00007FF7A50379EF+4456495]\nE       \tGetHandleVerifier [0x00007FF7A4CE0576+953270]\nE       \t(No symbol) [0x00007FF7A4B7E54F]\nE       \t(No symbol) [0x00007FF7A4B79224]\nE       \t(No symbol) [0x00007FF7A4B7935B]\nE       \t(No symbol) [0x00007FF7A4B69B94]\nE       \tBaseThreadInitThunk [0x00007FFF7A33257D+29]\nE       \tRtlUserThreadStart [0x00007FFF7B7AAA58+40]\n\n.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:229: NoSuchElementException\n\nDuring handling of the above exception, another exception occurred:\n\nself = <testCases.test_Login_params.Test_CredKart_Login_params object at 0x0000029F9254E8A0>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"c027018ef95d152f24d859d623f612f4\")>\ngetDataforLogin = ('Credence@234test.com', 'Credence@9656')\n\n    def test_CredKart_Login_parms_003(self, setup, getDataforLogin):\n    \n        self.driver = setup\n        self.driver.get(\"https://automation.credence.in/login\")\n        self.driver.maximize_window()\n        self.driver.find_element(By.XPATH, \"//input[@id='email']\").send_keys(getDataforLogin[0])\n        self.driver.find_element(By.XPATH, \"//input[@id='password']\").send_keys(getDataforLogin[1])\n        self.driver.find_element(By.XPATH, \"//button[@type='submit']\").click()\n        try:\n            self.driver.find_element(By.XPATH, \"//h2[normalize-space()='CredKart']\")\n            print(\"login test is passed\")\n            self.driver.save_screenshot(\".\\\\Screenshots\\\\test_Login_002_pass.PNG\")\n            self.driver.close()\n    \n            assert True\n    \n        except:\n            print(\"login test is Failed\")\n            self.driver.save_screenshot(\".\\\\Screenshots\\\\test_Login_002_fail.PNG\")\n            self.driver.close()\n>           assert False\nE           assert False\n\ntestCases\\test_Login_params.py:27: AssertionError"}, "parameters": [{"name": "getDataforLogin", "value": "('Credence@234test.com', 'Credence@9656')"}], "start": 1712822090274, "stop": 1712822103525, "uuid": "af47ffd0-c97e-424f-b3df-0a7d53d497e8", "historyId": "5318e4dc1ae0bfc6f7196f8470a8ac79", "testCaseId": "bad1ad50c93efd5cd9ef7b5cc7f37bb4", "fullName": "testCases.test_Login_params.Test_CredKart_Login_params#test_CredKart_Login_parms_003", "labels": [{"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "test_Login_params"}, {"name": "subSuite", "value": "Test_CredKart_Login_params"}, {"name": "host", "value": "Nikhil"}, {"name": "thread", "value": "15464-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.test_Login_params"}]}