{"uuid": "d5cbc986-e80e-4b6e-8268-b8a2ad760067", "children": ["5be9e928-2b8c-424d-bae8-ede4f51f7195"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=123.0.6312.106)\nStacktrace:\n\tGetHandleVerifier [0x00007FF69DFA70C2+63090]\n\t(No symbol) [0x00007FF69DF12D12]\n\t(No symbol) [0x00007FF69DDAEC65]\n\t(No symbol) [0x00007FF69DDAAC1A]\n\t(No symbol) [0x00007FF69DD9D514]\n\t(No symbol) [0x00007FF69DD9E8F8]\n\t(No symbol) [0x00007FF69DD9D7FF]\n\t(No symbol) [0x00007FF69DD9D104]\n\t(No symbol) [0x00007FF69DD9D021]\n\t(No symbol) [0x00007FF69DD9B0A8]\n\t(No symbol) [0x00007FF69DD9B8BC]\n\t(No symbol) [0x00007FF69DDB14AD]\n\t(No symbol) [0x00007FF69DE33D67]\n\t(No symbol) [0x00007FF69DE16FDA]\n\t(No symbol) [0x00007FF69DE33412]\n\t(No symbol) [0x00007FF69DE16D83]\n\t(No symbol) [0x00007FF69DDE83A8]\n\t(No symbol) [0x00007FF69DDE9441]\n\tGetHandleVerifier [0x00007FF69E3A262D+4238301]\n\tGetHandleVerifier [0x00007FF69E3DF78D+4488509]\n\tGetHandleVerifier [0x00007FF69E3D7A6F+4456479]\n\tGetHandleVerifier [0x00007FF69E080606+953270]\n\t(No symbol) [0x00007FF69DF1E5DF]\n\t(No symbol) [0x00007FF69DF192B4]\n\t(No symbol) [0x00007FF69DF193EB]\n\t(No symbol) [0x00007FF69DF09C24]\n\tBaseThreadInitThunk [0x00007FFF7A33257D+29]\n\tRtlUserThreadStart [0x00007FFF7B7AAA58+40]\n\n", "trace": "  File \"C:\\Users\\nikhi\\PycharmProjects\\CredeKart_Pytest_Project\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\nikhi\\PycharmProjects\\CredeKart_Pytest_Project\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\nikhi\\PycharmProjects\\CredeKart_Pytest_Project\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\nikhi\\PycharmProjects\\CredeKart_Pytest_Project\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\nikhi\\PycharmProjects\\CredeKart_Pytest_Project\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\nikhi\\PycharmProjects\\CredeKart_Pytest_Project\\testCases\\conftest.py\", line 41, in setup\n    driver.get(\"https://automation.credence.in\")\n  File \"C:\\Users\\nikhi\\PycharmProjects\\CredeKart_Pytest_Project\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 356, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\nikhi\\PycharmProjects\\CredeKart_Pytest_Project\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\nikhi\\PycharmProjects\\CredeKart_Pytest_Project\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1712862805134, "stop": 1712862808637}], "start": 1712862805134, "stop": 1712862808895}